### ISSUE TITLE
when try to do npm start error

### ISSUE THREAD

**Issue by lyminster** [vladotesanovic/angular2-quickstart-ngsemantic#2]
when i try to do npm start it show me this error

D:\Project\angular2-quickstart-ngsemantic-master>npm start

> angular2-quickstart-ngSemantic@0.0.1 start D:\Project\angular2-quickstart-ngsemantic-master
> tsc && concurrently "npm run tsc:w" "npm run lite"

app/routes.ts(2,50): error TS2305: Module '"D:/Project/angular2-quickstart-ngsemantic-master/node_modules/@angular/common/index"' has no exported member 'Type'.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Rommy Gautanto\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-quickstart-ngSemantic@0.0.1 start: `tsc && concurrently "npm run tsc:w" "npm run lite"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular2-quickstart-ngSemantic@0.0.1 start script 'tsc && concurrently "npm run tsc:w" "npm run lite" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-quickstart-ngSemantic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm run tsc:w" "npm run lite"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-quickstart-ngSemantic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-quickstart-ngSemantic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Project\angular2-quickstart-ngsemantic-master\npm-debug.log

**Comment by khuongduybui** [comment]
Fix:

``` diff
diff --git a/app/routes.ts b/app/routes.ts
index a92f5be..9643b59 100644
--- a/app/routes.ts
+++ b/app/routes.ts
@@ -1,5 +1,6 @@
 import { provideRouter, RouterConfig } from '@angular/router';
-import { LocationStrategy, HashLocationStrategy, Type } from "@angular/common";
+import { LocationStrategy, HashLocationStrategy } from "@angular/common";
+import { Type } from "@angular/core";

 import { HomeComponent } from './components/home/home.component';
 import { ReviewComponent } from './components/reviews/reviews.component';
```
